#ifndef QGSLLINEARFITTING_H_DEF
#define QGSLLINEARFITTING_H_DEF

#include <QObject>
#include "gslns.h"

PORTO_BEGIN_NAMESPACE
GSL_BEGIN_NAMESPACE

GSL_END_NAMESPACE
PORTO_END_NAMESPACE

#endif // QGSLLINEARFITTING_H_DEF
