// This file is autogenerated
// class: Example, 
// version: 1.0
// author: Thomas F. Hagelien


var $Qty = require('utils.quantities');

function Example (n_,m_) {
  this.dimensions = {
    N:n_,
    M:m_
  };


  this.len = new $Qty('cm');;
  this.y = new $Qty('m');;
  this.xs =_.range(n_).map(function(){
    return _.range(m_).map(function(){
      return new $Qty('m');
    });
  });

};
