#include <cstring>
#include <iostream>
#include <QtCore>
#include <Soft>
#include <softc/softc-datamodel-private.hpp>
#include "xy.hxx"  // Autogenerated

#include "xyplot.h"

int softc_plugin_identify (char* name, int maxlen) {
  const char plugin_name[] = "xyplot";
  const size_t len = std::min<size_t>(sizeof(plugin_name), maxlen);
  strncpy(name, plugin_name, len);
  name[len - 1] = '\0';
  return SOFTC_STATUS_OK;
}

int softc_plugin_capabilities ()
{
  return SOFTC_CAPABILITY_READ|SOFTC_CAPABILITY_WRITE;
}

int softc_plugin_load (softc_datamodel_t* datamodel, char const *uri, char const* options)
{
  using namespace soft;
  QUrl const loc(uri);
  QString filePath = loc.path();
  
  return SOFTC_STATUS_FAILURE;
}

int softc_plugin_save(softc_datamodel_t const* datamodel, const char* uri, const char* options)
{
  using namespace soft;
  QUrl loc(uri);
  QString filePath = loc.path();

  return SOFTC_STATUS_FAILURE;
}
